import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import * as docusign from 'docusign-esign';
import { ContractStatus } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { EncryptionService } from '../common/encryption.service';

@Injectable()
export class DocumentsService {
  private readonly logger = new Logger(DocumentsService.name);

  constructor(
    private prisma: PrismaService,
    private encryption: EncryptionService,
    private config: ConfigService,
  ) {}

  // Pre-fill ID407 (HK Immigration standard FDH contract) — OUTPUT: PDF only, no e-sign
  async generateId407(contractId: string): Promise<Buffer> {
    const contract = await this.prisma.contract.findUnique({ where: { id: contractId } });
    const employer = await this.prisma.employer.findUnique({ where: { id: contract.employerId } });
    const helper = await this.prisma.helper.findUnique({ where: { id: contract.helperId } });

    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([595, 842]); // A4
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const { width, height } = page.getSize();

    // Header
    page.drawText('STANDARD EMPLOYMENT CONTRACT', {
      x: 50, y: height - 60,
      font: boldFont, size: 16, color: rgb(0, 0, 0),
    });
    page.drawText('FOR FOREIGN DOMESTIC HELPERS (ID407)', {
      x: 50, y: height - 80,
      font: boldFont, size: 12, color: rgb(0.3, 0.3, 0.3),
    });
    page.drawText('Hong Kong Immigration Department', {
      x: 50, y: height - 100,
      font, size: 10, color: rgb(0.5, 0.5, 0.5),
    });

    // Employer section
    page.drawText('PART I — EMPLOYER DETAILS', {
      x: 50, y: height - 150,
      font: boldFont, size: 11,
    });
    page.drawText(`Name: ${employer.fullName}`, { x: 50, y: height - 170, font, size: 10 });
    page.drawText(`District: ${employer.district || 'N/A'}`, { x: 50, y: height - 185, font, size: 10 });

    // Helper section
    page.drawText('PART II — HELPER DETAILS', {
      x: 50, y: height - 220,
      font: boldFont, size: 11,
    });
    page.drawText(`Name: ${helper.fullName}`, { x: 50, y: height - 240, font, size: 10 });
    page.drawText(`Nationality: ${helper.nationality}`, { x: 50, y: height - 255, font, size: 10 });

    // Contract terms
    page.drawText('PART III — CONTRACT TERMS', {
      x: 50, y: height - 290,
      font: boldFont, size: 11,
    });
    if (contract.startDate) {
      page.drawText(`Start Date: ${contract.startDate.toLocaleDateString('en-HK')}`, {
        x: 50, y: height - 310, font, size: 10,
      });
    }
    if (contract.endDate) {
      page.drawText(`End Date: ${contract.endDate.toLocaleDateString('en-HK')}`, {
        x: 50, y: height - 325, font, size: 10,
      });
    }

    // Important notice
    page.drawText(
      '⚠ IMPORTANT: This form must be printed and signed physically.',
      { x: 50, y: height - 380, font: boldFont, size: 9, color: rgb(0.8, 0, 0) },
    );
    page.drawText(
      'The Immigration Department does NOT accept electronic signatures for ID407.',
      { x: 50, y: height - 395, font, size: 9, color: rgb(0.8, 0, 0) },
    );

    // Signature blocks
    page.drawText('Employer Signature: ___________________', { x: 50, y: 120, font, size: 10 });
    page.drawText('Helper Signature: ___________________', { x: 320, y: 120, font, size: 10 });
    page.drawText('Date: ___________________', { x: 50, y: 100, font, size: 10 });

    // Footer
    page.drawText(`Generated by MatchAI • ${new Date().toLocaleDateString('en-HK')}`, {
      x: 50, y: 40, font, size: 8, color: rgb(0.6, 0.6, 0.6),
    });

    const pdfBytes = await pdfDoc.save();
    return Buffer.from(pdfBytes);
  }

  // Service & Agency Agreement — CAN be e-signed via DocuSign
  async sendSsaForSignature(contractId: string) {
    const contract = await this.prisma.contract.findUnique({ where: { id: contractId } });
    const employer = await this.prisma.employer.findUnique({
      where: { id: contract.employerId },
      include: { user: true },
    });
    const helper = await this.prisma.helper.findUnique({
      where: { id: contract.helperId },
      include: { user: true },
    });

    const ssaPdf = await this.generateSsaPdf(employer, helper, contract);

    const apiClient = new docusign.ApiClient();
    apiClient.setBasePath('https://demo.docusign.net/restapi');
    apiClient.addDefaultHeader('Authorization', `Bearer ${await this.getDocuSignToken()}`);

    const envelopesApi = new docusign.EnvelopesApi(apiClient);

    const envelope = {
      emailSubject: 'MatchAI Service & Agency Agreement — Please Sign',
      documents: [{
        documentBase64: ssaPdf.toString('base64'),
        name: 'Service_Agency_Agreement.pdf',
        fileExtension: 'pdf',
        documentId: '1',
      }],
      recipients: {
        signers: [
          {
            email: employer.user.email,
            name: employer.fullName,
            recipientId: '1',
            routingOrder: '1',
            tabs: {
              signHereTabs: [{ anchorString: '[[EMPLOYER_SIGN]]', anchorUnits: 'pixels' }],
            },
          },
          {
            email: helper.user.email,
            name: helper.fullName,
            recipientId: '2',
            routingOrder: '2',
            tabs: {
              signHereTabs: [{ anchorString: '[[HELPER_SIGN]]', anchorUnits: 'pixels' }],
            },
          },
        ],
      },
      status: 'sent',
    };

    const result = await envelopesApi.createEnvelope(
      this.config.get('DOCUSIGN_ACCOUNT_ID'),
      { envelopeDefinition: envelope },
    );

    await this.prisma.contract.update({
      where: { id: contractId },
      data: {
        docusignEnvelopeId: result.envelopeId,
        status: ContractStatus.PENDING_SIGNATURE,
      },
    });

    return { envelopeId: result.envelopeId, status: 'sent' };
  }

  // Escrow release notice PDF — triggered by Stripe webhook
  async generateEscrowReleaseNotice(paymentId: string): Promise<Buffer> {
    const payment = await this.prisma.payment.findUnique({
      where: { id: paymentId },
      include: { employer: true, broker: true },
    });

    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([595, 420]);
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const { height } = page.getSize();

    page.drawText('ESCROW RELEASE NOTICE', {
      x: 50, y: height - 60, font: boldFont, size: 18,
    });
    page.drawText('MatchAI Platform', { x: 50, y: height - 82, font, size: 11, color: rgb(0.4, 0.4, 0.4) });

    page.drawText(`Payment ID: ${payment.id}`, { x: 50, y: height - 130, font, size: 10 });
    page.drawText(`Employer: ${payment.employer.fullName}`, { x: 50, y: height - 150, font, size: 10 });
    page.drawText(`Broker Agency: ${payment.broker?.agencyName || 'N/A'}`, { x: 50, y: height - 165, font, size: 10 });
    page.drawText(
      `Total Amount: HKD ${((payment.amount) / 100).toLocaleString()}`,
      { x: 50, y: height - 185, font: boldFont, size: 11 },
    );
    page.drawText(
      `Platform Fee: HKD ${((payment.platformFee) / 100).toLocaleString()}`,
      { x: 50, y: height - 205, font, size: 10 },
    );
    page.drawText(
      `Broker Payout: HKD ${((payment.brokerAmount) / 100).toLocaleString()}`,
      { x: 50, y: height - 220, font, size: 10 },
    );
    page.drawText(
      `Release Date: ${payment.transferredAt?.toLocaleDateString('en-HK') || 'Pending'}`,
      { x: 50, y: height - 240, font, size: 10 },
    );
    page.drawText(
      `Stripe Transfer ID: ${payment.stripeTransferId || 'Pending'}`,
      { x: 50, y: height - 255, font, size: 10 },
    );

    page.drawText(
      `Generated by MatchAI • ${new Date().toLocaleDateString('en-HK')}`,
      { x: 50, y: 30, font, size: 8, color: rgb(0.6, 0.6, 0.6) },
    );

    return Buffer.from(await pdfDoc.save());
  }

  private async generateSsaPdf(employer: any, helper: any, contract: any): Promise<Buffer> {
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([595, 842]);
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const { height } = page.getSize();

    page.drawText('SERVICE & AGENCY AGREEMENT', { x: 50, y: height - 60, font: boldFont, size: 16 });
    page.drawText('MatchAI Platform', { x: 50, y: height - 82, font, size: 11, color: rgb(0.4, 0.4, 0.4) });

    page.drawText(`This agreement is between MatchAI Platform, ${employer.fullName} (Employer),`, {
      x: 50, y: height - 130, font, size: 10,
    });
    page.drawText(`and ${helper.fullName} (Helper/Worker), effective from the date of signing.`, {
      x: 50, y: height - 145, font, size: 10,
    });

    page.drawText('EMPLOYER SIGNATURE: [[EMPLOYER_SIGN]]', { x: 50, y: 100, font: boldFont, size: 10 });
    page.drawText('HELPER SIGNATURE: [[HELPER_SIGN]]', { x: 50, y: 70, font: boldFont, size: 10 });

    return Buffer.from(await pdfDoc.save());
  }

  private async getDocuSignToken(): Promise<string> {
    // In production: use DocuSign JWT Grant authentication
    // For now, return config token placeholder
    return this.config.get('DOCUSIGN_ACCESS_TOKEN', '');
  }
}
